import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CreateEventDrawer } from "@/components/createEvent";

const outFit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="scroll-smooth hide-scroll "
      suppressContentEditableWarning
      suppressHydrationWarning
    >
      <ClerkProvider>
        <body className={`${outFit.className}  antialiased`}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
          <CreateEventDrawer />
        </body>
      </ClerkProvider>
    </html>
  );
}
